import type { Metadata } from "next";
import { Inter, Sedan } from "next/font/google";
import "./globals.css";
import MobileNavbar from "@/animated-components/mobile-navbar-1";

const inter = Inter({ subsets: ["latin"] });
const sedan = Sedan({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sedan.className}>
        <header>
          <MobileNavbar />
        </header>
        {children}
      </body>
    </html>
  );
}
